name: Semantic Release

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      ref:
        type: string
        description: git ref to checkout
        required: false
        default: ${{ github.sha }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create tags and releases
    steps:
      - name: Checkout to specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Create temporary local release branch
        id: temp_branch
        run: |
          TEMP_BRANCH_NAME="temprelease/${{ inputs.ref }}"
          git branch "$TEMP_BRANCH_NAME"
          git checkout "$TEMP_BRANCH_NAME"
          echo "branch_name=$TEMP_BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Current branch is $(git rev-parse --abbrev-ref HEAD) at commit $(git rev-parse HEAD)"
          echo "Source branch for history analysis by semantic-release is effectively leading up to this commit."

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_PARENT_PAGE_ID: ${{ secrets.CONFLUENCE_PARENT_PAGE_ID }}

      - name: Clean up temporary branch (optional but good practice)
        if: always() # Run even if semantic-release fails, to ensure cleanup
        run: |
          echo "Switching back to the original source branch ref locally (detached HEAD)"
          git checkout ${{ inputs.ref }}
            
          TEMP_BRANCH_NAME="temprelease/${{ inputs.ref }}"
          echo "Deleting local temporary branch $TEMP_BRANCH_NAME"
          git branch -D "$TEMP_BRANCH_NAME"
          echo "Local branches:"
          git branch
