name: Semantic Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows pushing to the repo
      issues: write # Optional: for closing issues
      pull-requests: write # Optional: for PR references
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Debug Confluence credentials
        run: |
          echo "CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME != '' && '***' || 'NOT SET' }}"
          echo "CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN != '' && '***' || 'NOT SET' }}"
          echo "CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL != '' && '***' || 'NOT SET' }}"

      - name: Test Confluence API Access
        env:
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
        run: |
          # Test listing spaces (replace with your domain)
          curl -u "$CONFLUENCE_USERNAME:$CONFLUENCE_API_TOKEN" \
            "$CONFLUENCE_URL"

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
